-- MySQL Script generated by MySQL Workbench
-- Sun May 19 21:06:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema servicios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema servicios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `servicios` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `servicios` ;

-- -----------------------------------------------------
-- Table `servicios`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicios`.`categorias` (
  `categorias_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL DEFAULT NULL,
  `descrip` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`categorias_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `servicios`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicios`.`pagos` (
  `pagos_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` TEXT NULL DEFAULT NULL,
  `cantidad` INT(100) NULL DEFAULT NULL,
  PRIMARY KEY (`pagos_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `servicios`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicios`.`usuarios` (
  `usuarios_id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`usuarios_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `servicios`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicios`.`servicios` (
  `servicios_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `usuarios_id` INT(11) NULL DEFAULT NULL,
  `categorias_id` INT(11) NULL DEFAULT NULL,
  `descrip` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`servicios_id`),
  INDEX `usuarios_id` (`usuarios_id` ASC) VISIBLE,
  INDEX `categorias_id` (`categorias_id` ASC) VISIBLE,
  CONSTRAINT `servicios_ibfk_1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `servicios`.`usuarios` (`usuarios_id`),
  CONSTRAINT `servicios_ibfk_2`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `servicios`.`categorias` (`categorias_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `servicios`.`transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicios`.`transacciones` (
  `transacciones_id` INT(11) NOT NULL AUTO_INCREMENT,
  `servicios_id` INT(11) NULL DEFAULT NULL,
  `estado` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`transacciones_id`),
  INDEX `servicios_id` (`servicios_id` ASC) VISIBLE,
  CONSTRAINT `transacciones_ibfk_1`
    FOREIGN KEY (`servicios_id`)
    REFERENCES `servicios`.`servicios` (`servicios_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `servicios`.`usuariosypagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicios`.`usuariosypagos` (
  `pagos_id` INT(11) NULL DEFAULT NULL,
  `usuarios_orig_id` INT(11) NULL DEFAULT NULL,
  `usuarios_dest_id` INT(11) NULL DEFAULT NULL,
  INDEX `usuarios_orig_id` (`usuarios_orig_id` ASC) VISIBLE,
  INDEX `usuarios_dest_id` (`usuarios_dest_id` ASC) VISIBLE,
  INDEX `pagos_id` (`pagos_id` ASC) VISIBLE,
  CONSTRAINT `usuariosypagos_ibfk_1`
    FOREIGN KEY (`usuarios_orig_id`)
    REFERENCES `servicios`.`usuarios` (`usuarios_id`),
  CONSTRAINT `usuariosypagos_ibfk_2`
    FOREIGN KEY (`usuarios_dest_id`)
    REFERENCES `servicios`.`usuarios` (`usuarios_id`),
  CONSTRAINT `usuariosypagos_ibfk_3`
    FOREIGN KEY (`pagos_id`)
    REFERENCES `servicios`.`pagos` (`pagos_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `servicios`.`usuariosytransacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicios`.`usuariosytransacciones` (
  `transacciones_id` INT(11) NULL DEFAULT NULL,
  `usuarios_orig_id` INT(11) NULL DEFAULT NULL,
  `usuarios_dest_id` INT(11) NULL DEFAULT NULL,
  INDEX `usuarios_orig_id` (`usuarios_orig_id` ASC) VISIBLE,
  INDEX `usuarios_dest_id` (`usuarios_dest_id` ASC) VISIBLE,
  INDEX `transacciones_id` (`transacciones_id` ASC) VISIBLE,
  CONSTRAINT `usuariosytransacciones_ibfk_1`
    FOREIGN KEY (`usuarios_orig_id`)
    REFERENCES `servicios`.`usuarios` (`usuarios_id`),
  CONSTRAINT `usuariosytransacciones_ibfk_2`
    FOREIGN KEY (`usuarios_dest_id`)
    REFERENCES `servicios`.`usuarios` (`usuarios_id`),
  CONSTRAINT `usuariosytransacciones_ibfk_3`
    FOREIGN KEY (`transacciones_id`)
    REFERENCES `servicios`.`transacciones` (`transacciones_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `servicios` ;

-- -----------------------------------------------------
-- procedure usuariosAddOrEdit
-- -----------------------------------------------------

DELIMITER $$
USE `servicios`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `usuariosAddOrEdit`(
  IN _id INT,
  IN _username VARCHAR(45),
  IN _email TEXT
)
BEGIN 
  IF _id = 0 THEN
    INSERT INTO usuarios (username, email)
    VALUES (_username, _email);

    SET _id = LAST_INSERT_ID();
  ELSE
    UPDATE usuarios
    SET
    username = _username,
    email = _email
    WHERE id = _id;
  END IF;

  SELECT _id AS 'id';
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
